// Legacy SR treeData id compatibility map (baseline-aligned for downstream plugins)
//
// Some baseline meta uses historical ids for trace nodes, while Hakush provides PointID values.
// We keep both id spaces in treeData by duplicating entries at generation time.
//
// NOTE: This file is auto-generated by scripts/gen-sr-treeData-id-compat.mjs.

export type SrTreeDataCompatEntry = { fromPointId: number; idx?: number }

export const srTreeDataIdCompat: Record<string, Record<string, SrTreeDataCompatEntry>> = {
  "1001": {
    "877640": {
      "fromPointId": 1001101,
      "idx": 2
    },
    "877642": {
      "fromPointId": 1001103,
      "idx": 1
    },
    "877643": {
      "fromPointId": 1001102,
      "idx": 3
    },
    "877732": {
      "fromPointId": 1001206
    },
    "877733": {
      "fromPointId": 1001207
    },
    "877734": {
      "fromPointId": 1001204
    },
    "877735": {
      "fromPointId": 1001205
    },
    "877736": {
      "fromPointId": 1001202
    },
    "877737": {
      "fromPointId": 1001203
    },
    "877739": {
      "fromPointId": 1001201
    },
    "877746": {
      "fromPointId": 1001208
    },
    "877747": {
      "fromPointId": 1001209
    },
    "961679": {
      "fromPointId": 1001210
    }
  },
  "1002": {
    "124180": {
      "fromPointId": 1002210
    },
    "240727": {
      "fromPointId": 1002101
    },
    "240729": {
      "fromPointId": 1002103
    },
    "240730": {
      "fromPointId": 1002102
    },
    "240819": {
      "fromPointId": 1002206
    },
    "240820": {
      "fromPointId": 1002207
    },
    "240821": {
      "fromPointId": 1002204
    },
    "240822": {
      "fromPointId": 1002205
    },
    "240823": {
      "fromPointId": 1002202
    },
    "240824": {
      "fromPointId": 1002203
    },
    "240826": {
      "fromPointId": 1002201
    },
    "240833": {
      "fromPointId": 1002208
    },
    "240834": {
      "fromPointId": 1002209
    }
  },
  "1003": {
    "202642": {
      "fromPointId": 1003101
    },
    "202644": {
      "fromPointId": 1003103
    },
    "202645": {
      "fromPointId": 1003102
    },
    "202734": {
      "fromPointId": 1003206
    },
    "202735": {
      "fromPointId": 1003207
    },
    "202736": {
      "fromPointId": 1003204
    },
    "202737": {
      "fromPointId": 1003205
    },
    "202738": {
      "fromPointId": 1003202
    },
    "202739": {
      "fromPointId": 1003203
    },
    "202741": {
      "fromPointId": 1003201
    },
    "202748": {
      "fromPointId": 1003208
    },
    "202749": {
      "fromPointId": 1003209
    },
    "286681": {
      "fromPointId": 1003210
    }
  },
  "1004": {
    "149174": {
      "fromPointId": 1004210
    },
    "233017": {
      "fromPointId": 1004101
    },
    "233019": {
      "fromPointId": 1004103
    },
    "233020": {
      "fromPointId": 1004102
    },
    "233109": {
      "fromPointId": 1004206
    },
    "233110": {
      "fromPointId": 1004207
    },
    "233111": {
      "fromPointId": 1004204
    },
    "233112": {
      "fromPointId": 1004205
    },
    "233113": {
      "fromPointId": 1004202
    },
    "233114": {
      "fromPointId": 1004203
    },
    "233116": {
      "fromPointId": 1004201
    },
    "233123": {
      "fromPointId": 1004208
    },
    "233124": {
      "fromPointId": 1004209
    }
  },
  "1008": {
    "99186": {
      "fromPointId": 1008210
    },
    "215733": {
      "fromPointId": 1008101
    },
    "215735": {
      "fromPointId": 1008103
    },
    "215736": {
      "fromPointId": 1008102
    },
    "215825": {
      "fromPointId": 1008206
    },
    "215826": {
      "fromPointId": 1008207
    },
    "215827": {
      "fromPointId": 1008204
    },
    "215828": {
      "fromPointId": 1008205
    },
    "215829": {
      "fromPointId": 1008202
    },
    "215830": {
      "fromPointId": 1008203
    },
    "215832": {
      "fromPointId": 1008201
    },
    "215839": {
      "fromPointId": 1008208
    },
    "215840": {
      "fromPointId": 1008209
    }
  },
  "1009": {
    "177648": {
      "fromPointId": 1009101
    },
    "177650": {
      "fromPointId": 1009103
    },
    "177651": {
      "fromPointId": 1009102
    },
    "177740": {
      "fromPointId": 1009206
    },
    "177741": {
      "fromPointId": 1009207
    },
    "177742": {
      "fromPointId": 1009204
    },
    "177743": {
      "fromPointId": 1009205
    },
    "177744": {
      "fromPointId": 1009202
    },
    "177745": {
      "fromPointId": 1009203
    },
    "177747": {
      "fromPointId": 1009201
    },
    "177754": {
      "fromPointId": 1009208
    },
    "177755": {
      "fromPointId": 1009209
    },
    "294391": {
      "fromPointId": 1009210
    }
  },
  "1013": {
    "205779": {
      "fromPointId": 1013101
    },
    "205780": {
      "fromPointId": 1013102
    },
    "205781": {
      "fromPointId": 1013103
    },
    "205934": {
      "fromPointId": 1013207
    },
    "205935": {
      "fromPointId": 1013206
    },
    "205936": {
      "fromPointId": 1013205
    },
    "205937": {
      "fromPointId": 1013204
    },
    "205938": {
      "fromPointId": 1013203
    },
    "205939": {
      "fromPointId": 1013202
    },
    "205940": {
      "fromPointId": 1013201
    },
    "205948": {
      "fromPointId": 1013209
    },
    "205949": {
      "fromPointId": 1013208
    },
    "289882": {
      "fromPointId": 1013210
    }
  },
  "1101": {
    "189034": {
      "fromPointId": 1101210
    },
    "272877": {
      "fromPointId": 1101101
    },
    "272879": {
      "fromPointId": 1101103
    },
    "272880": {
      "fromPointId": 1101102
    },
    "272969": {
      "fromPointId": 1101206
    },
    "272970": {
      "fromPointId": 1101207
    },
    "272971": {
      "fromPointId": 1101204
    },
    "272972": {
      "fromPointId": 1101205
    },
    "272973": {
      "fromPointId": 1101202
    },
    "272974": {
      "fromPointId": 1101203
    },
    "272976": {
      "fromPointId": 1101201
    },
    "272983": {
      "fromPointId": 1101208
    },
    "272984": {
      "fromPointId": 1101209
    }
  },
  "1102": {
    "310962": {
      "fromPointId": 1102101
    },
    "310964": {
      "fromPointId": 1102103,
      "idx": 2
    },
    "310965": {
      "fromPointId": 1102102,
      "idx": 3
    },
    "311054": {
      "fromPointId": 1102206
    },
    "311055": {
      "fromPointId": 1102207
    },
    "311056": {
      "fromPointId": 1102204
    },
    "311057": {
      "fromPointId": 1102205
    },
    "311058": {
      "fromPointId": 1102202
    },
    "311059": {
      "fromPointId": 1102203
    },
    "311061": {
      "fromPointId": 1102201
    },
    "311068": {
      "fromPointId": 1102208
    },
    "311069": {
      "fromPointId": 1102209
    },
    "395001": {
      "fromPointId": 1102210
    }
  },
  "1103": {
    "514036": {
      "fromPointId": 1103210
    },
    "597879": {
      "fromPointId": 1103101
    },
    "597881": {
      "fromPointId": 1103103
    },
    "597882": {
      "fromPointId": 1103102
    },
    "597971": {
      "fromPointId": 1103206
    },
    "597972": {
      "fromPointId": 1103207
    },
    "597973": {
      "fromPointId": 1103204
    },
    "597974": {
      "fromPointId": 1103205
    },
    "597975": {
      "fromPointId": 1103202
    },
    "597976": {
      "fromPointId": 1103203
    },
    "597978": {
      "fromPointId": 1103201
    },
    "597985": {
      "fromPointId": 1103208
    },
    "597986": {
      "fromPointId": 1103209
    }
  },
  "1104": {
    "303252": {
      "fromPointId": 1104101,
      "idx": 2
    },
    "303254": {
      "fromPointId": 1104103,
      "idx": 1
    },
    "303255": {
      "fromPointId": 1104102,
      "idx": 3
    },
    "303344": {
      "fromPointId": 1104206
    },
    "303345": {
      "fromPointId": 1104207
    },
    "303346": {
      "fromPointId": 1104204
    },
    "303347": {
      "fromPointId": 1104205
    },
    "303348": {
      "fromPointId": 1104202
    },
    "303349": {
      "fromPointId": 1104203
    },
    "303351": {
      "fromPointId": 1104201
    },
    "303358": {
      "fromPointId": 1104208
    },
    "303359": {
      "fromPointId": 1104209
    },
    "419995": {
      "fromPointId": 1104210
    }
  },
  "1105": {
    "506326": {
      "fromPointId": 1105210
    },
    "622873": {
      "fromPointId": 1105101
    },
    "622875": {
      "fromPointId": 1105103
    },
    "622876": {
      "fromPointId": 1105102
    },
    "622965": {
      "fromPointId": 1105206
    },
    "622966": {
      "fromPointId": 1105207
    },
    "622967": {
      "fromPointId": 1105204
    },
    "622968": {
      "fromPointId": 1105205
    },
    "622969": {
      "fromPointId": 1105202
    },
    "622970": {
      "fromPointId": 1105203
    },
    "622972": {
      "fromPointId": 1105201
    },
    "622979": {
      "fromPointId": 1105208
    },
    "622980": {
      "fromPointId": 1105209
    }
  },
  "1106": {
    "660958": {
      "fromPointId": 1106101
    },
    "660960": {
      "fromPointId": 1106103
    },
    "660961": {
      "fromPointId": 1106102
    },
    "661050": {
      "fromPointId": 1106206
    },
    "661051": {
      "fromPointId": 1106207
    },
    "661052": {
      "fromPointId": 1106204
    },
    "661053": {
      "fromPointId": 1106205
    },
    "661054": {
      "fromPointId": 1106202
    },
    "661055": {
      "fromPointId": 1106203
    },
    "661057": {
      "fromPointId": 1106201
    },
    "661064": {
      "fromPointId": 1106208
    },
    "661065": {
      "fromPointId": 1106209
    },
    "744997": {
      "fromPointId": 1106210
    }
  },
  "1107": {
    "864032": {
      "fromPointId": 1107210
    },
    "947875": {
      "fromPointId": 1107101
    },
    "947877": {
      "fromPointId": 1107103
    },
    "947878": {
      "fromPointId": 1107102
    },
    "947967": {
      "fromPointId": 1107206
    },
    "947968": {
      "fromPointId": 1107207
    },
    "947969": {
      "fromPointId": 1107204
    },
    "947970": {
      "fromPointId": 1107205
    },
    "947971": {
      "fromPointId": 1107202
    },
    "947972": {
      "fromPointId": 1107203
    },
    "947974": {
      "fromPointId": 1107201
    },
    "947981": {
      "fromPointId": 1107208
    },
    "947982": {
      "fromPointId": 1107209
    }
  },
  "1108": {
    "285968": {
      "fromPointId": 1108101,
      "idx": 3
    },
    "285970": {
      "fromPointId": 1108103,
      "idx": 2
    },
    "285971": {
      "fromPointId": 1108102,
      "idx": 1
    },
    "286060": {
      "fromPointId": 1108206
    },
    "286061": {
      "fromPointId": 1108207
    },
    "286062": {
      "fromPointId": 1108204
    },
    "286063": {
      "fromPointId": 1108205
    },
    "286064": {
      "fromPointId": 1108202
    },
    "286065": {
      "fromPointId": 1108203
    },
    "286067": {
      "fromPointId": 1108201
    },
    "286074": {
      "fromPointId": 1108208
    },
    "286075": {
      "fromPointId": 1108209
    },
    "370007": {
      "fromPointId": 1108210
    }
  },
  "1109": {
    "489042": {
      "fromPointId": 1109210
    },
    "572885": {
      "fromPointId": 1109101
    },
    "572887": {
      "fromPointId": 1109103
    },
    "572888": {
      "fromPointId": 1109102
    },
    "572977": {
      "fromPointId": 1109206
    },
    "572978": {
      "fromPointId": 1109207
    },
    "572979": {
      "fromPointId": 1109204
    },
    "572980": {
      "fromPointId": 1109205
    },
    "572981": {
      "fromPointId": 1109202
    },
    "572982": {
      "fromPointId": 1109203
    },
    "572984": {
      "fromPointId": 1109201
    },
    "572991": {
      "fromPointId": 1109208
    },
    "572992": {
      "fromPointId": 1109209
    }
  },
  "1110": {
    "73200": {
      "fromPointId": 1110210
    },
    "989097": {
      "fromPointId": 1110101
    },
    "989098": {
      "fromPointId": 1110102
    },
    "989099": {
      "fromPointId": 1110103
    },
    "989252": {
      "fromPointId": 1110207
    },
    "989253": {
      "fromPointId": 1110206
    },
    "989254": {
      "fromPointId": 1110205
    },
    "989255": {
      "fromPointId": 1110204
    },
    "989256": {
      "fromPointId": 1110203
    },
    "989257": {
      "fromPointId": 1110202
    },
    "989258": {
      "fromPointId": 1110201
    },
    "989266": {
      "fromPointId": 1110209
    },
    "989267": {
      "fromPointId": 1110208
    }
  },
  "1111": {
    "192235": {
      "fromPointId": 1111210
    },
    "276014": {
      "fromPointId": 1111101
    },
    "276015": {
      "fromPointId": 1111102
    },
    "276016": {
      "fromPointId": 1111103
    },
    "276169": {
      "fromPointId": 1111207
    },
    "276170": {
      "fromPointId": 1111206
    },
    "276171": {
      "fromPointId": 1111205
    },
    "276172": {
      "fromPointId": 1111204
    },
    "276173": {
      "fromPointId": 1111203
    },
    "276174": {
      "fromPointId": 1111202
    },
    "276175": {
      "fromPointId": 1111201
    },
    "276183": {
      "fromPointId": 1111209
    },
    "276184": {
      "fromPointId": 1111208
    }
  },
  "1112": {
    "314099": {
      "fromPointId": 1112101
    },
    "314100": {
      "fromPointId": 1112102
    },
    "314101": {
      "fromPointId": 1112103
    },
    "314254": {
      "fromPointId": 1112207
    },
    "314255": {
      "fromPointId": 1112206
    },
    "314256": {
      "fromPointId": 1112205
    },
    "314257": {
      "fromPointId": 1112204
    },
    "314258": {
      "fromPointId": 1112203
    },
    "314259": {
      "fromPointId": 1112202
    },
    "314260": {
      "fromPointId": 1112201
    },
    "314268": {
      "fromPointId": 1112209
    },
    "314269": {
      "fromPointId": 1112208
    },
    "398202": {
      "fromPointId": 1112210
    }
  },
  "1201": {
    "668114": {
      "fromPointId": 1201101
    },
    "668116": {
      "fromPointId": 1201103
    },
    "668117": {
      "fromPointId": 1201102
    },
    "668206": {
      "fromPointId": 1201206
    },
    "668207": {
      "fromPointId": 1201207
    },
    "668208": {
      "fromPointId": 1201204
    },
    "668209": {
      "fromPointId": 1201205
    },
    "668210": {
      "fromPointId": 1201202
    },
    "668211": {
      "fromPointId": 1201203
    },
    "668213": {
      "fromPointId": 1201201
    },
    "668220": {
      "fromPointId": 1201208
    },
    "668221": {
      "fromPointId": 1201209
    },
    "752153": {
      "fromPointId": 1201210
    }
  },
  "1202": {
    "264650": {
      "fromPointId": 1202210
    },
    "381197": {
      "fromPointId": 1202101
    },
    "381199": {
      "fromPointId": 1202103,
      "idx": 2
    },
    "381200": {
      "fromPointId": 1202102,
      "idx": 3
    },
    "381289": {
      "fromPointId": 1202206
    },
    "381290": {
      "fromPointId": 1202207
    },
    "381291": {
      "fromPointId": 1202204
    },
    "381292": {
      "fromPointId": 1202205
    },
    "381293": {
      "fromPointId": 1202202
    },
    "381294": {
      "fromPointId": 1202203
    },
    "381296": {
      "fromPointId": 1202201
    },
    "381303": {
      "fromPointId": 1202208
    },
    "381304": {
      "fromPointId": 1202209
    }
  },
  "1203": {
    "343112": {
      "fromPointId": 1203101,
      "idx": 3
    },
    "343114": {
      "fromPointId": 1203103,
      "idx": 2
    },
    "343115": {
      "fromPointId": 1203102,
      "idx": 1
    },
    "343204": {
      "fromPointId": 1203206
    },
    "343205": {
      "fromPointId": 1203207
    },
    "343206": {
      "fromPointId": 1203204
    },
    "343207": {
      "fromPointId": 1203205
    },
    "343208": {
      "fromPointId": 1203202
    },
    "343209": {
      "fromPointId": 1203203
    },
    "343211": {
      "fromPointId": 1203201
    },
    "343218": {
      "fromPointId": 1203208
    },
    "343219": {
      "fromPointId": 1203209
    },
    "427151": {
      "fromPointId": 1203210
    }
  },
  "1204": {
    "56195": {
      "fromPointId": 1204101
    },
    "56197": {
      "fromPointId": 1204103
    },
    "56198": {
      "fromPointId": 1204102
    },
    "56287": {
      "fromPointId": 1204206
    },
    "56288": {
      "fromPointId": 1204207
    },
    "56289": {
      "fromPointId": 1204204
    },
    "56290": {
      "fromPointId": 1204205
    },
    "56291": {
      "fromPointId": 1204202
    },
    "56292": {
      "fromPointId": 1204203
    },
    "56294": {
      "fromPointId": 1204201
    },
    "56301": {
      "fromPointId": 1204208
    },
    "56302": {
      "fromPointId": 1204209
    },
    "939648": {
      "fromPointId": 1204210
    }
  },
  "1206": {
    "614646": {
      "fromPointId": 1206210
    },
    "731193": {
      "fromPointId": 1206101
    },
    "731195": {
      "fromPointId": 1206103
    },
    "731196": {
      "fromPointId": 1206102
    },
    "731285": {
      "fromPointId": 1206206
    },
    "731286": {
      "fromPointId": 1206207
    },
    "731287": {
      "fromPointId": 1206204
    },
    "731288": {
      "fromPointId": 1206205
    },
    "731289": {
      "fromPointId": 1206202
    },
    "731290": {
      "fromPointId": 1206203
    },
    "731292": {
      "fromPointId": 1206201
    },
    "731299": {
      "fromPointId": 1206208
    },
    "731300": {
      "fromPointId": 1206209
    }
  },
  "1207": {
    "693108": {
      "fromPointId": 1207101,
      "idx": 3
    },
    "693110": {
      "fromPointId": 1207103,
      "idx": 2
    },
    "693111": {
      "fromPointId": 1207102,
      "idx": 1
    },
    "693200": {
      "fromPointId": 1207206
    },
    "693201": {
      "fromPointId": 1207207
    },
    "693202": {
      "fromPointId": 1207204
    },
    "693203": {
      "fromPointId": 1207205
    },
    "693204": {
      "fromPointId": 1207202
    },
    "693205": {
      "fromPointId": 1207203
    },
    "693207": {
      "fromPointId": 1207201
    },
    "693214": {
      "fromPointId": 1207208
    },
    "693215": {
      "fromPointId": 1207209
    },
    "777147": {
      "fromPointId": 1207210
    }
  },
  "1208": {
    "6207": {
      "fromPointId": 1208101,
      "idx": 3
    },
    "6209": {
      "fromPointId": 1208103,
      "idx": 1
    },
    "6210": {
      "fromPointId": 1208102
    },
    "6299": {
      "fromPointId": 1208206
    },
    "6300": {
      "fromPointId": 1208207
    },
    "6301": {
      "fromPointId": 1208204
    },
    "6302": {
      "fromPointId": 1208205
    },
    "6303": {
      "fromPointId": 1208202
    },
    "6304": {
      "fromPointId": 1208203
    },
    "6306": {
      "fromPointId": 1208201
    },
    "6313": {
      "fromPointId": 1208208
    },
    "6314": {
      "fromPointId": 1208209
    },
    "922364": {
      "fromPointId": 1208210
    }
  },
  "1209": {
    "84865": {
      "fromPointId": 1209210
    },
    "968122": {
      "fromPointId": 1209101
    },
    "968124": {
      "fromPointId": 1209103
    },
    "968125": {
      "fromPointId": 1209102
    },
    "968214": {
      "fromPointId": 1209206
    },
    "968215": {
      "fromPointId": 1209207
    },
    "968216": {
      "fromPointId": 1209204
    },
    "968217": {
      "fromPointId": 1209205
    },
    "968218": {
      "fromPointId": 1209202
    },
    "968219": {
      "fromPointId": 1209203
    },
    "968221": {
      "fromPointId": 1209201
    },
    "968228": {
      "fromPointId": 1209208
    },
    "968229": {
      "fromPointId": 1209209
    }
  },
  "1210": {
    "592853": {
      "fromPointId": 1210210
    },
    "709336": {
      "fromPointId": 1210101
    },
    "709337": {
      "fromPointId": 1210102
    },
    "709338": {
      "fromPointId": 1210103
    },
    "709491": {
      "fromPointId": 1210207
    },
    "709492": {
      "fromPointId": 1210206
    },
    "709493": {
      "fromPointId": 1210205
    },
    "709494": {
      "fromPointId": 1210204
    },
    "709495": {
      "fromPointId": 1210203
    },
    "709496": {
      "fromPointId": 1210202
    },
    "709497": {
      "fromPointId": 1210201
    },
    "709505": {
      "fromPointId": 1210209
    },
    "709506": {
      "fromPointId": 1210208
    }
  },
  "1211": {
    "671251": {
      "fromPointId": 1211101
    },
    "671252": {
      "fromPointId": 1211102
    },
    "671253": {
      "fromPointId": 1211103
    },
    "671406": {
      "fromPointId": 1211207
    },
    "671407": {
      "fromPointId": 1211206
    },
    "671408": {
      "fromPointId": 1211205
    },
    "671409": {
      "fromPointId": 1211204
    },
    "671410": {
      "fromPointId": 1211203
    },
    "671411": {
      "fromPointId": 1211202
    },
    "671412": {
      "fromPointId": 1211201
    },
    "671420": {
      "fromPointId": 1211209
    },
    "671421": {
      "fromPointId": 1211208
    },
    "755354": {
      "fromPointId": 1211210
    }
  },
  "1213": {
    "346249": {
      "fromPointId": 1213101
    },
    "346250": {
      "fromPointId": 1213102
    },
    "346251": {
      "fromPointId": 1213103
    },
    "346404": {
      "fromPointId": 1213207
    },
    "346405": {
      "fromPointId": 1213206
    },
    "346406": {
      "fromPointId": 1213205
    },
    "346407": {
      "fromPointId": 1213204
    },
    "346408": {
      "fromPointId": 1213203
    },
    "346409": {
      "fromPointId": 1213202
    },
    "346410": {
      "fromPointId": 1213201
    },
    "346418": {
      "fromPointId": 1213209
    },
    "346419": {
      "fromPointId": 1213208
    },
    "430352": {
      "fromPointId": 1213210
    }
  },
  "1214": {
    "59332": {
      "fromPointId": 1214101
    },
    "59333": {
      "fromPointId": 1214102
    },
    "59334": {
      "fromPointId": 1214103
    },
    "59487": {
      "fromPointId": 1214207
    },
    "59488": {
      "fromPointId": 1214206
    },
    "59489": {
      "fromPointId": 1214205
    },
    "59490": {
      "fromPointId": 1214204
    },
    "59491": {
      "fromPointId": 1214203
    },
    "59492": {
      "fromPointId": 1214202
    },
    "59493": {
      "fromPointId": 1214201
    },
    "59501": {
      "fromPointId": 1214209
    },
    "59502": {
      "fromPointId": 1214208
    },
    "942849": {
      "fromPointId": 1214210
    }
  },
  "1215": {
    "21247": {
      "fromPointId": 1215101
    },
    "21248": {
      "fromPointId": 1215102
    },
    "21249": {
      "fromPointId": 1215103
    },
    "21402": {
      "fromPointId": 1215207
    },
    "21403": {
      "fromPointId": 1215206
    },
    "21404": {
      "fromPointId": 1215205
    },
    "21405": {
      "fromPointId": 1215204
    },
    "21406": {
      "fromPointId": 1215203
    },
    "21407": {
      "fromPointId": 1215202
    },
    "21408": {
      "fromPointId": 1215201
    },
    "21416": {
      "fromPointId": 1215209
    },
    "21417": {
      "fromPointId": 1215208
    },
    "105350": {
      "fromPointId": 1215210
    }
  },
  "1217": {
    "696245": {
      "fromPointId": 1217101,
      "idx": 3
    },
    "696246": {
      "fromPointId": 1217102,
      "idx": 1
    },
    "696247": {
      "fromPointId": 1217103,
      "idx": 2
    },
    "696400": {
      "fromPointId": 1217207
    },
    "696401": {
      "fromPointId": 1217206
    },
    "696402": {
      "fromPointId": 1217205
    },
    "696403": {
      "fromPointId": 1217204
    },
    "696404": {
      "fromPointId": 1217203
    },
    "696405": {
      "fromPointId": 1217202
    },
    "696406": {
      "fromPointId": 1217201
    },
    "696414": {
      "fromPointId": 1217209
    },
    "696415": {
      "fromPointId": 1217208
    },
    "780348": {
      "fromPointId": 1217210
    }
  },
  "1218": {
    "9344": {
      "fromPointId": 1218101
    },
    "9345": {
      "fromPointId": 1218102
    },
    "9346": {
      "fromPointId": 1218103
    },
    "9499": {
      "fromPointId": 1218207
    },
    "9500": {
      "fromPointId": 1218206
    },
    "9501": {
      "fromPointId": 1218205
    },
    "9502": {
      "fromPointId": 1218204
    },
    "9503": {
      "fromPointId": 1218203
    },
    "9504": {
      "fromPointId": 1218202
    },
    "9505": {
      "fromPointId": 1218201
    },
    "9513": {
      "fromPointId": 1218209
    },
    "9514": {
      "fromPointId": 1218208
    },
    "925565": {
      "fromPointId": 1218210
    }
  },
  "1220": {
    "591698": {
      "fromPointId": 1220210
    },
    "708339": {
      "fromPointId": 1220204
    },
    "708340": {
      "fromPointId": 1220205
    },
    "708341": {
      "fromPointId": 1220206
    },
    "708342": {
      "fromPointId": 1220207
    },
    "708344": {
      "fromPointId": 1220201
    },
    "708345": {
      "fromPointId": 1220202
    },
    "708346": {
      "fromPointId": 1220203
    },
    "708351": {
      "fromPointId": 1220208
    },
    "708352": {
      "fromPointId": 1220209
    },
    "708375": {
      "fromPointId": 1220103
    },
    "708376": {
      "fromPointId": 1220102
    },
    "708377": {
      "fromPointId": 1220101
    }
  },
  "1221": {
    "670254": {
      "fromPointId": 1221204
    },
    "670255": {
      "fromPointId": 1221205
    },
    "670256": {
      "fromPointId": 1221206
    },
    "670257": {
      "fromPointId": 1221207
    },
    "670259": {
      "fromPointId": 1221201
    },
    "670260": {
      "fromPointId": 1221202
    },
    "670261": {
      "fromPointId": 1221203
    },
    "670266": {
      "fromPointId": 1221208
    },
    "670267": {
      "fromPointId": 1221209
    },
    "670290": {
      "fromPointId": 1221103
    },
    "670291": {
      "fromPointId": 1221102
    },
    "670292": {
      "fromPointId": 1221101
    },
    "754199": {
      "fromPointId": 1221210
    }
  },
  "1222": {
    "266696": {
      "fromPointId": 1222210
    },
    "383337": {
      "fromPointId": 1222204
    },
    "383338": {
      "fromPointId": 1222205
    },
    "383339": {
      "fromPointId": 1222206
    },
    "383340": {
      "fromPointId": 1222207
    },
    "383342": {
      "fromPointId": 1222201
    },
    "383343": {
      "fromPointId": 1222202
    },
    "383344": {
      "fromPointId": 1222203
    },
    "383349": {
      "fromPointId": 1222208
    },
    "383350": {
      "fromPointId": 1222209
    },
    "383373": {
      "fromPointId": 1222103
    },
    "383374": {
      "fromPointId": 1222102
    },
    "383375": {
      "fromPointId": 1222101
    }
  },
  "1223": {
    "345252": {
      "fromPointId": 1223204
    },
    "345253": {
      "fromPointId": 1223205
    },
    "345254": {
      "fromPointId": 1223206
    },
    "345255": {
      "fromPointId": 1223207
    },
    "345257": {
      "fromPointId": 1223201
    },
    "345258": {
      "fromPointId": 1223202
    },
    "345259": {
      "fromPointId": 1223203
    },
    "345264": {
      "fromPointId": 1223208
    },
    "345265": {
      "fromPointId": 1223209
    },
    "345288": {
      "fromPointId": 1223103
    },
    "345289": {
      "fromPointId": 1223102
    },
    "345290": {
      "fromPointId": 1223101
    },
    "429197": {
      "fromPointId": 1223210
    }
  },
  "1225": {
    "20250": {
      "fromPointId": 1225204
    },
    "20251": {
      "fromPointId": 1225205
    },
    "20252": {
      "fromPointId": 1225206
    },
    "20253": {
      "fromPointId": 1225207
    },
    "20255": {
      "fromPointId": 1225201
    },
    "20256": {
      "fromPointId": 1225202
    },
    "20257": {
      "fromPointId": 1225203
    },
    "20262": {
      "fromPointId": 1225208
    },
    "20263": {
      "fromPointId": 1225209
    },
    "20286": {
      "fromPointId": 1225103
    },
    "20287": {
      "fromPointId": 1225102
    },
    "20288": {
      "fromPointId": 1225101
    },
    "104195": {
      "fromPointId": 1225210
    }
  },
  "1301": {
    "63351": {
      "fromPointId": 1301101
    },
    "63353": {
      "fromPointId": 1301103
    },
    "63354": {
      "fromPointId": 1301102
    },
    "63443": {
      "fromPointId": 1301206
    },
    "63444": {
      "fromPointId": 1301207
    },
    "63445": {
      "fromPointId": 1301204
    },
    "63446": {
      "fromPointId": 1301205
    },
    "63447": {
      "fromPointId": 1301202
    },
    "63448": {
      "fromPointId": 1301203
    },
    "63450": {
      "fromPointId": 1301201
    },
    "63457": {
      "fromPointId": 1301208
    },
    "63458": {
      "fromPointId": 1301209
    },
    "979508": {
      "fromPointId": 1301210
    }
  },
  "1302": {
    "451432": {
      "fromPointId": 1302101
    },
    "451434": {
      "fromPointId": 1302103,
      "idx": 2
    },
    "451435": {
      "fromPointId": 1302102,
      "idx": 3
    },
    "451524": {
      "fromPointId": 1302206
    },
    "451525": {
      "fromPointId": 1302207
    },
    "451526": {
      "fromPointId": 1302204
    },
    "451527": {
      "fromPointId": 1302205
    },
    "451528": {
      "fromPointId": 1302202
    },
    "451529": {
      "fromPointId": 1302203
    },
    "451531": {
      "fromPointId": 1302201
    },
    "451538": {
      "fromPointId": 1302208
    },
    "451539": {
      "fromPointId": 1302209
    },
    "535471": {
      "fromPointId": 1302210
    }
  },
  "1303": {
    "654506": {
      "fromPointId": 1303210
    },
    "738349": {
      "fromPointId": 1303101
    },
    "738351": {
      "fromPointId": 1303103
    },
    "738352": {
      "fromPointId": 1303102
    },
    "738441": {
      "fromPointId": 1303206
    },
    "738442": {
      "fromPointId": 1303207
    },
    "738443": {
      "fromPointId": 1303204
    },
    "738444": {
      "fromPointId": 1303205
    },
    "738445": {
      "fromPointId": 1303202
    },
    "738446": {
      "fromPointId": 1303203
    },
    "738448": {
      "fromPointId": 1303201
    },
    "738455": {
      "fromPointId": 1303208
    },
    "738456": {
      "fromPointId": 1303209
    }
  },
  "1304": {
    "126430": {
      "fromPointId": 1304101,
      "idx": 2
    },
    "126432": {
      "fromPointId": 1304103,
      "idx": 1
    },
    "126433": {
      "fromPointId": 1304102,
      "idx": 3
    },
    "126522": {
      "fromPointId": 1304206
    },
    "126523": {
      "fromPointId": 1304207
    },
    "126524": {
      "fromPointId": 1304204
    },
    "126525": {
      "fromPointId": 1304205
    },
    "126526": {
      "fromPointId": 1304202
    },
    "126527": {
      "fromPointId": 1304203
    },
    "126529": {
      "fromPointId": 1304201
    },
    "126536": {
      "fromPointId": 1304208
    },
    "126537": {
      "fromPointId": 1304209
    },
    "210469": {
      "fromPointId": 1304210
    }
  },
  "1305": {
    "329504": {
      "fromPointId": 1305210
    },
    "413347": {
      "fromPointId": 1305101,
      "idx": 2
    },
    "413349": {
      "fromPointId": 1305103
    },
    "413350": {
      "fromPointId": 1305102,
      "idx": 1
    },
    "413439": {
      "fromPointId": 1305206
    },
    "413440": {
      "fromPointId": 1305207
    },
    "413441": {
      "fromPointId": 1305204
    },
    "413442": {
      "fromPointId": 1305205
    },
    "413443": {
      "fromPointId": 1305202
    },
    "413444": {
      "fromPointId": 1305203
    },
    "413446": {
      "fromPointId": 1305201
    },
    "413453": {
      "fromPointId": 1305208
    },
    "413454": {
      "fromPointId": 1305209
    }
  },
  "1306": {
    "801428": {
      "fromPointId": 1306101
    },
    "801430": {
      "fromPointId": 1306103
    },
    "801431": {
      "fromPointId": 1306102
    },
    "801520": {
      "fromPointId": 1306206
    },
    "801521": {
      "fromPointId": 1306207
    },
    "801522": {
      "fromPointId": 1306204
    },
    "801523": {
      "fromPointId": 1306205
    },
    "801524": {
      "fromPointId": 1306202
    },
    "801525": {
      "fromPointId": 1306203
    },
    "801527": {
      "fromPointId": 1306201
    },
    "801534": {
      "fromPointId": 1306208
    },
    "801535": {
      "fromPointId": 1306209
    },
    "885467": {
      "fromPointId": 1306210
    }
  },
  "1307": {
    "4502": {
      "fromPointId": 1307210
    },
    "88345": {
      "fromPointId": 1307101
    },
    "88347": {
      "fromPointId": 1307103
    },
    "88348": {
      "fromPointId": 1307102
    },
    "88437": {
      "fromPointId": 1307206
    },
    "88438": {
      "fromPointId": 1307207
    },
    "88439": {
      "fromPointId": 1307204
    },
    "88440": {
      "fromPointId": 1307205
    },
    "88441": {
      "fromPointId": 1307202
    },
    "88442": {
      "fromPointId": 1307203
    },
    "88444": {
      "fromPointId": 1307201
    },
    "88451": {
      "fromPointId": 1307208
    },
    "88452": {
      "fromPointId": 1307209
    }
  },
  "1308": {
    "76442": {
      "fromPointId": 1308101
    },
    "76444": {
      "fromPointId": 1308103
    },
    "76445": {
      "fromPointId": 1308102
    },
    "76534": {
      "fromPointId": 1308206
    },
    "76535": {
      "fromPointId": 1308207
    },
    "76536": {
      "fromPointId": 1308204
    },
    "76537": {
      "fromPointId": 1308205
    },
    "76538": {
      "fromPointId": 1308202
    },
    "76539": {
      "fromPointId": 1308203
    },
    "76541": {
      "fromPointId": 1308201
    },
    "76548": {
      "fromPointId": 1308208
    },
    "76549": {
      "fromPointId": 1308209
    },
    "160481": {
      "fromPointId": 1308210
    }
  },
  "1309": {
    "279516": {
      "fromPointId": 1309210
    },
    "363359": {
      "fromPointId": 1309101
    },
    "363361": {
      "fromPointId": 1309103
    },
    "363362": {
      "fromPointId": 1309102
    },
    "363451": {
      "fromPointId": 1309206
    },
    "363452": {
      "fromPointId": 1309207
    },
    "363453": {
      "fromPointId": 1309204
    },
    "363454": {
      "fromPointId": 1309205
    },
    "363455": {
      "fromPointId": 1309202
    },
    "363456": {
      "fromPointId": 1309203
    },
    "363458": {
      "fromPointId": 1309201
    },
    "363465": {
      "fromPointId": 1309208
    },
    "363466": {
      "fromPointId": 1309209
    }
  },
  "1310": {
    "779571": {
      "fromPointId": 1310101
    },
    "779572": {
      "fromPointId": 1310102
    },
    "779573": {
      "fromPointId": 1310103
    },
    "779726": {
      "fromPointId": 1310207
    },
    "779727": {
      "fromPointId": 1310206
    },
    "779728": {
      "fromPointId": 1310205
    },
    "779729": {
      "fromPointId": 1310204
    },
    "779730": {
      "fromPointId": 1310203
    },
    "779731": {
      "fromPointId": 1310202
    },
    "779732": {
      "fromPointId": 1310201
    },
    "779740": {
      "fromPointId": 1310209
    },
    "779741": {
      "fromPointId": 1310208
    },
    "863674": {
      "fromPointId": 1310210
    }
  },
  "1312": {
    "454569": {
      "fromPointId": 1312101
    },
    "454570": {
      "fromPointId": 1312102
    },
    "454571": {
      "fromPointId": 1312103
    },
    "454724": {
      "fromPointId": 1312207
    },
    "454725": {
      "fromPointId": 1312206
    },
    "454726": {
      "fromPointId": 1312205
    },
    "454727": {
      "fromPointId": 1312204
    },
    "454728": {
      "fromPointId": 1312203
    },
    "454729": {
      "fromPointId": 1312202
    },
    "454730": {
      "fromPointId": 1312201
    },
    "454738": {
      "fromPointId": 1312209
    },
    "454739": {
      "fromPointId": 1312208
    },
    "538672": {
      "fromPointId": 1312210
    }
  },
  "1313": {
    "657707": {
      "fromPointId": 1313210
    },
    "741486": {
      "fromPointId": 1313101
    },
    "741487": {
      "fromPointId": 1313102
    },
    "741488": {
      "fromPointId": 1313103
    },
    "741641": {
      "fromPointId": 1313207
    },
    "741642": {
      "fromPointId": 1313206
    },
    "741643": {
      "fromPointId": 1313205
    },
    "741644": {
      "fromPointId": 1313204
    },
    "741645": {
      "fromPointId": 1313203
    },
    "741646": {
      "fromPointId": 1313202
    },
    "741647": {
      "fromPointId": 1313201
    },
    "741655": {
      "fromPointId": 1313209
    },
    "741656": {
      "fromPointId": 1313208
    }
  },
  "1314": {
    "129567": {
      "fromPointId": 1314101
    },
    "129568": {
      "fromPointId": 1314102
    },
    "129569": {
      "fromPointId": 1314103
    },
    "129722": {
      "fromPointId": 1314207
    },
    "129723": {
      "fromPointId": 1314206
    },
    "129724": {
      "fromPointId": 1314205
    },
    "129725": {
      "fromPointId": 1314204
    },
    "129726": {
      "fromPointId": 1314203
    },
    "129727": {
      "fromPointId": 1314202
    },
    "129728": {
      "fromPointId": 1314201
    },
    "129736": {
      "fromPointId": 1314209
    },
    "129737": {
      "fromPointId": 1314208
    },
    "213670": {
      "fromPointId": 1314210
    }
  },
  "1315": {
    "332705": {
      "fromPointId": 1315210
    },
    "416484": {
      "fromPointId": 1315101
    },
    "416485": {
      "fromPointId": 1315102
    },
    "416486": {
      "fromPointId": 1315103
    },
    "416639": {
      "fromPointId": 1315207
    },
    "416640": {
      "fromPointId": 1315206
    },
    "416641": {
      "fromPointId": 1315205
    },
    "416642": {
      "fromPointId": 1315204
    },
    "416643": {
      "fromPointId": 1315203
    },
    "416644": {
      "fromPointId": 1315202
    },
    "416645": {
      "fromPointId": 1315201
    },
    "416653": {
      "fromPointId": 1315209
    },
    "416654": {
      "fromPointId": 1315208
    }
  },
  "1317": {
    "7703": {
      "fromPointId": 1317210
    },
    "91482": {
      "fromPointId": 1317101
    },
    "91483": {
      "fromPointId": 1317102
    },
    "91484": {
      "fromPointId": 1317103
    },
    "91637": {
      "fromPointId": 1317207
    },
    "91638": {
      "fromPointId": 1317206
    },
    "91639": {
      "fromPointId": 1317205
    },
    "91640": {
      "fromPointId": 1317204
    },
    "91641": {
      "fromPointId": 1317203
    },
    "91642": {
      "fromPointId": 1317202
    },
    "91643": {
      "fromPointId": 1317201
    },
    "91651": {
      "fromPointId": 1317209
    },
    "91652": {
      "fromPointId": 1317208
    }
  },
  "1401": {
    "13154185": {
      "fromPointId": 1401210
    },
    "29382444": {
      "fromPointId": 1401103
    },
    "29473604": {
      "fromPointId": 1401101
    },
    "29648208": {
      "fromPointId": 1401102
    },
    "29941205": {
      "fromPointId": 1401208
    },
    "30026159": {
      "fromPointId": 1401202
    },
    "30106081": {
      "fromPointId": 1401206
    },
    "30115214": {
      "fromPointId": 1401204
    },
    "30205990": {
      "fromPointId": 1401209
    },
    "30284611": {
      "fromPointId": 1401201
    },
    "30347253": {
      "fromPointId": 1401207
    },
    "30364560": {
      "fromPointId": 1401205
    },
    "30406588": {
      "fromPointId": 1401203
    }
  },
  "1402": {
    "12718379": {
      "fromPointId": 1402206
    },
    "12722920": {
      "fromPointId": 1402103
    },
    "12743939": {
      "fromPointId": 1402208
    },
    "12779200": {
      "fromPointId": 1402101
    },
    "12802457": {
      "fromPointId": 1402202
    },
    "12828018": {
      "fromPointId": 1402204
    },
    "12993337": {
      "fromPointId": 1402207
    },
    "13018908": {
      "fromPointId": 1402209
    },
    "13029630": {
      "fromPointId": 1402102
    },
    "13055887": {
      "fromPointId": 1402201
    },
    "13077350": {
      "fromPointId": 1402203
    },
    "13102918": {
      "fromPointId": 1402205
    },
    "29542769": {
      "fromPointId": 1402210
    }
  },
  "1403": {
    "9530676": {
      "fromPointId": 1403208
    },
    "9540978": {
      "fromPointId": 1403204
    },
    "9554261": {
      "fromPointId": 1403206
    },
    "9567439": {
      "fromPointId": 1403103
    },
    "9580479": {
      "fromPointId": 1403201
    },
    "9585560": {
      "fromPointId": 1403203
    },
    "9591024": {
      "fromPointId": 1403101
    },
    "9748226": {
      "fromPointId": 1403209
    },
    "9771817": {
      "fromPointId": 1403207
    },
    "9824065": {
      "fromPointId": 1403205
    },
    "9841376": {
      "fromPointId": 1403102
    },
    "9859470": {
      "fromPointId": 1403202
    },
    "26247257": {
      "fromPointId": 1403210
    }
  },
  "1404": {
    "7350792": {
      "fromPointId": 1404208
    },
    "7509123": {
      "fromPointId": 1404201
    },
    "7549118": {
      "fromPointId": 1404203
    },
    "7593053": {
      "fromPointId": 1404205
    },
    "7603236": {
      "fromPointId": 1404209
    },
    "7633013": {
      "fromPointId": 1404207
    },
    "7816850": {
      "fromPointId": 1404202
    },
    "7835235": {
      "fromPointId": 1404206
    },
    "7856718": {
      "fromPointId": 1404204
    },
    "7930452": {
      "fromPointId": 1404101
    },
    "7956081": {
      "fromPointId": 1404103
    },
    "8204354": {
      "fromPointId": 1404102
    },
    "24179113": {
      "fromPointId": 1404210
    }
  },
  "1405": {
    "10266835": {
      "fromPointId": 1405210
    },
    "26884624": {
      "fromPointId": 1405202
    },
    "26891607": {
      "fromPointId": 1405102
    },
    "26893883": {
      "fromPointId": 1405204
    },
    "26936970": {
      "fromPointId": 1405208
    },
    "26993375": {
      "fromPointId": 1405206
    },
    "27141957": {
      "fromPointId": 1405103
    },
    "27159586": {
      "fromPointId": 1405203
    },
    "27164842": {
      "fromPointId": 1405101
    },
    "27183110": {
      "fromPointId": 1405201
    },
    "27228312": {
      "fromPointId": 1405209
    },
    "27242703": {
      "fromPointId": 1405205
    },
    "27251955": {
      "fromPointId": 1405207
    }
  },
  "1406": {
    "3266892": {
      "fromPointId": 1406201
    },
    "3292452": {
      "fromPointId": 1406203
    },
    "3314175": {
      "fromPointId": 1406205
    },
    "3339738": {
      "fromPointId": 1406207
    },
    "3353022": {
      "fromPointId": 1406209
    },
    "3534640": {
      "fromPointId": 1406202
    },
    "3556113": {
      "fromPointId": 1406204
    },
    "3581929": {
      "fromPointId": 1406206
    },
    "3611594": {
      "fromPointId": 1406208
    },
    "3694282": {
      "fromPointId": 1406101
    },
    "3901663": {
      "fromPointId": 1406102
    },
    "4176691": {
      "fromPointId": 1406103
    },
    "20413782": {
      "fromPointId": 1406210
    }
  },
  "1407": {
    "636727": {
      "fromPointId": 1407102
    },
    "875201": {
      "fromPointId": 1407103
    },
    "885030": {
      "fromPointId": 1407101
    },
    "1080336": {
      "fromPointId": 1407207
    },
    "1085508": {
      "fromPointId": 1407209
    },
    "1245350": {
      "fromPointId": 1407201
    },
    "1287390": {
      "fromPointId": 1407203
    },
    "1300735": {
      "fromPointId": 1407205
    },
    "1322499": {
      "fromPointId": 1407206
    },
    "1327658": {
      "fromPointId": 1407208
    },
    "1529520": {
      "fromPointId": 1407202
    },
    "1542891": {
      "fromPointId": 1407204
    },
    "18145452": {
      "fromPointId": 1407210
    }
  },
  "1409": {
    "977288": {
      "fromPointId": 1409210
    },
    "17316017": {
      "fromPointId": 1409101
    },
    "17319061": {
      "fromPointId": 1409103
    },
    "17447393": {
      "fromPointId": 1409209
    },
    "17456576": {
      "fromPointId": 1409207
    },
    "17503611": {
      "fromPointId": 1409203
    },
    "17516886": {
      "fromPointId": 1409201
    },
    "17559847": {
      "fromPointId": 1409205
    },
    "17590951": {
      "fromPointId": 1409102
    },
    "17698770": {
      "fromPointId": 1409208
    },
    "17791848": {
      "fromPointId": 1409202
    },
    "17802038": {
      "fromPointId": 1409206
    },
    "17811211": {
      "fromPointId": 1409204
    }
  }
}
